const Courses = [
    {
        id: "1",
        title: "Web Development",
        image: require('../../assets/logo_education.jpg'),
        description: "Lorem Ipsum dolor sit amet, consectetuer adipising elit. Aenean commodo ligula eget dolor adipiscing elit.",
        course1: "HTML",
        course2: "CSS",
        course3: "Javascript",
        price: 5000,
    },
    {
        id: "2",
        title: "Design Development",
        image: require('../../assets/logo_education.jpg'),
        description: "Lorem Ipsum dolor sit amet, consectetuer adipising elit. Aenean commodo ligula eget dolor adipiscing elit.",
        course1: "HTML",
        course2: "CSS",
        course3: "Bootstrap",
        price: 3000,
    },
    {
        id: "3",
        title: "Full Stack Development",
        image: require('../../assets/logo_education.jpg'),
        description: "Lorem Ipsum dolor sit amet, consectetuer adipising elit. Aenean commodo ligula eget dolor adipiscing elit.",
        course1: "HTML",
        course2: "React",
        course3: "Node",
        price: 10000,
    },
    {
        id: "4",
        title: "Back End Development",
        image: require('../../assets/logo_education.jpg'),
        description: "Lorem Ipsum dolor sit amet, consectetuer adipising elit. Aenean commodo ligula eget dolor adipiscing elit.",
        course1: "Express",
        course2: "Mongoose",
        course3: "Node",
        price: 4000,
    },
    {
        id: "5",
        title: "Front End Development",
        image: require('../../assets/logo_education.jpg'),
        description: "Lorem Ipsum dolor sit amet, consectetuer adipising elit. Aenean commodo ligula eget dolor adipiscing elit.",
        course1: "HTML",
        course2: "CSS",
        course3: "React",
        price: 6000,
    },
]

export default Courses